### ISSUE TITLE
accessory needs updateRequest or it spams get-status

### ISSUE THREAD

**Issue by gabbas** [bugs181/homebridge-garadget-mqtt#1]
Thanks bugs this is really great!! While setting up your plugin I hit one snag that I thought you should know about. The example config on https://community.garadget.com/t/introducing-garadget-integration-for-homebridge-using-mqtt/6999 doesn't show an updateRequest parameter, and if you leave it out then the plugin will start sending repeated get-status messages as fast as it can until the Garadget crashes. I see the problem in the GaradgetAccessory ("if (config.updateRequest !== 0)") but I don't know enough JS to fix it. Probably you need to check whether it's undefined I guess, and then treat that as if it were 0? I then found the bundled example-config.json file which has the necessary parameters, and I realize if I had seen that first then I wouldn't have made this mistake. Anyway, I got it working now and it's awesome. Thanks again.

**Comment by bugs181** [comment]
Hey @gabbas, apologies for not seeing this issue sooner! I’ll take a look at the issue when I get some time. I appreciate the information and glad that you were able to find a fix. How has it been working out for you?

**Comment by gabbas** [comment]
No worries. Really good! Thanks for asking. I was sad to find out that Garadget went out of business, but with MQTT-based Siri integration it's been great. (I had trouble getting particle.io to work, and anyway didn't want to depend on the cloud in the first place.)

**Comment by bugs181** [comment]
This is the first I'm hearing of Garadget going out of business. Looked on their webpage/community forum but didn't see anything. Would you happen to have a link for me? I bought it with the intention to use local control. I never intended to use the cloud feature either.

Since I personally use this plugin, I'll continue to maintain it and add new features; however there's not many features that can be added due to the simplicity of the device in the first place.

**Comment by gabbas** [comment]
It was a particle.io support rep that said they were out of business. Now that you mention it you're right, it doesn't make sense because I bought my device from Garadget directly, less than a month ago. I'll follow up with him to see what he was thinking.

**Comment by bugs181** [comment]
It appears Garadget is still going strong. Closing this issue because I forgot to close it when I pushed the fix! Please re-open if you have any other issues.
